/**
 * Query-parameter types for the Financial Dashboard API calls.
 *
 * Each interface describes the query params sent to a backend endpoint. The
 * names, defaults and constraints were verified against the OpenAPI schema
 * generated by FastAPI (`/openapi.json`, served at `/docs`).
 *
 * Conventions:
 * - Strict TypeScript: no `any`, no `object`; enums are modeled as union types.
 * - Dates are always `string` in `YYYY-MM-DD` format (backend `date` type).
 * - Optional params that the backend default to `null` are typed as
 *   `type | null` and should be OMITTED from the query string when `null`.
 */
import type {
  BusinessType,
  Category,
  OperationType,
} from './api-types'

/** Valid grouping buckets for the summary/alerts endpoints. */
export type GroupBy = 'day' | 'week' | 'month'

/**
 * Type of the two date inputs used to filter the dashboard (Feature 1) and the
 * B2B vs B2C comparison (Feature 3). Both dates are optional; when `null` the
 * dashboard shows all available data.
 */
export interface DateRangeFilter {
  /**
   * Inclusive start of the range. Format: ISO-8601 `YYYY-MM-DD`.
   * `null` means "no lower bound" (all data from the beginning).
   */
  startDate: string | null
  /**
   * Inclusive end of the range. Format: ISO-8601 `YYYY-MM-DD`.
   * `null` means "no upper bound" (all data until the end).
   */
  endDate: string | null
}

/**
 * Query params for `GET /api/metrics/alerts` (Feature 2 — anomaly table).
 * Serializes to `threshold`, `group_by`, `start_date`, `end_date`, `business_type`.
 */
export interface AlertsParams {
  /**
   * Alert ratio threshold. A period is flagged when
   * `increase_ratio > threshold`. Valid range per OpenAPI: `>= 0`
   * (the UI must additionally cap it at 1.0 as per `prompst.md`). Default: `0.3`.
   */
  threshold: number
  /** Bucketing period for the anomaly detection. Default: `"month"`. */
  groupBy?: GroupBy
  /** Inclusive start date filter. Format: `YYYY-MM-DD`; omit/`null` to ignore. */
  startDate?: string | null
  /** Inclusive end date filter. Format: `YYYY-MM-DD`; omit/`null` to ignore. */
  endDate?: string | null
  /** Business line to restrict the analysis to. Values: `"B2B"` | `"B2C"`; omit/`null` for both. */
  businessType?: BusinessType | null
}

/**
 * Query params for `GET /api/metrics/categories/top` (Feature 3 — B2B vs B2C
 * category tables). Serializes to `operation_type`, `limit`, `start_date`,
 * `end_date`, `business_type`.
 */
export interface TopCategoriesParams {
  /** Operation type to aggregate. Valid values: `"income"`, `"outcome"`. Default: `"outcome"`. */
  operationType?: OperationType
  /**
   * Maximum number of categories to return. Default: `5`;
   * valid range per OpenAPI: `1`–`20`.
   */
  limit?: number
  /** Inclusive start date filter. Format: `YYYY-MM-DD`; omit/`null` to ignore. */
  startDate?: string | null
  /** Inclusive end date filter. Format: `YYYY-MM-DD`; omit/`null` to ignore. */
  endDate?: string | null
  /** Business line to restrict the analysis to. Values: `"B2B"` | `"B2C"`; omit/`null` for both. */
  businessType?: BusinessType | null
}

/**
 * Query params shared by the metrics endpoints that accept generic filters —
 * `GET /api/metrics`, `GET /api/metrics/summary`.
 */
export interface MetricsParams {
  /** Inclusive start date filter. Format: `YYYY-MM-DD`; omit/`null` to ignore. */
  startDate?: string | null
  /** Inclusive end date filter. Format: `YYYY-MM-DD`; omit/`null` to ignore. */
  endDate?: string | null
  /** Category to filter by; omit/`null` for all categories. */
  category?: Category | null
  /** Operation type to filter by; omit/`null` for both types. */
  operationType?: OperationType | null
  /** Business line to filter by; omit/`null` for both lines. */
  businessType?: BusinessType | null
}